//AUTOGENERATED FILE FROM png2asset
// Conversion args: gameover.png -c gameover.c -bpp 2 -noflip -keep_palette_order

#ifndef METASPRITE_gameover_H
#define METASPRITE_gameover_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define gameover_TILE_ORIGIN 0
#define gameover_TILE_W 8
#define gameover_TILE_H 16
#define gameover_WIDTH 80
#define gameover_HEIGHT 16
#define gameover_TILE_COUNT 20
#define gameover_PALETTE_COUNT 8
#define gameover_COLORS_PER_PALETTE 4
#define gameover_TOTAL_COLORS 32
#define gameover_PIVOT_X 40
#define gameover_PIVOT_Y 8
#define gameover_PIVOT_W 80
#define gameover_PIVOT_H 16
extern const metasprite_t* const gameover_metasprites[1];

BANKREF_EXTERN(gameover)

extern const palette_color_t gameover_palettes[32];
extern const uint8_t gameover_tiles[320];

#endif
