//AUTOGENERATED FILE FROM png2asset
// Conversion args: title_bg.png -c title_bg.c -map -bpp 2 -noflip -keep_palette_order

#ifndef METASPRITE_title_bg_H
#define METASPRITE_title_bg_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define title_bg_TILE_ORIGIN 0
#define title_bg_TILE_W 8
#define title_bg_TILE_H 8
#define title_bg_WIDTH 160
#define title_bg_HEIGHT 144
#define title_bg_TILE_COUNT 165
#define title_bg_PALETTE_COUNT 1
#define title_bg_COLORS_PER_PALETTE 4
#define title_bg_TOTAL_COLORS 4
#define title_bg_MAP_ATTRIBUTES 0
extern const unsigned char title_bg_map[360];
#define title_bg_map_attributes title_bg_map

BANKREF_EXTERN(title_bg)

extern const palette_color_t title_bg_palettes[4];
extern const uint8_t title_bg_tiles[2640];

#endif
