//AUTOGENERATED FILE FROM png2asset
// Conversion args: /final_victory.png -c /final_victory.c -map -bpp 2 -noflip -max_palettes 1

#ifndef METASPRITE_final_victory_H
#define METASPRITE_final_victory_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define final_victory_TILE_ORIGIN 0
#define final_victory_TILE_W 8
#define final_victory_TILE_H 8
#define final_victory_WIDTH 160
#define final_victory_HEIGHT 144
#define final_victory_TILE_COUNT 46
#define final_victory_PALETTE_COUNT 1
#define final_victory_COLORS_PER_PALETTE 4
#define final_victory_TOTAL_COLORS 4
#define final_victory_MAP_ATTRIBUTES 0
extern const unsigned char final_victory_map[360];
#define final_victory_map_attributes final_victory_map

BANKREF_EXTERN(final_victory)

extern const palette_color_t final_victory_palettes[4];
extern const uint8_t final_victory_tiles[736];

#endif
