//AUTOGENERATED FILE FROM png2asset
// Conversion args: /level_ui.png -c /level_ui.c -sw 8 -sh 16 -bpp 2 -noflip -keep_palette_order

#ifndef METASPRITE_level_ui_H
#define METASPRITE_level_ui_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define level_ui_TILE_ORIGIN 0
#define level_ui_TILE_W 8
#define level_ui_TILE_H 16
#define level_ui_WIDTH 8
#define level_ui_HEIGHT 16
#define level_ui_TILE_COUNT 24
#define level_ui_PALETTE_COUNT 8
#define level_ui_COLORS_PER_PALETTE 4
#define level_ui_TOTAL_COLORS 32
#define level_ui_PIVOT_X 4
#define level_ui_PIVOT_Y 8
#define level_ui_PIVOT_W 8
#define level_ui_PIVOT_H 16
extern const metasprite_t* const level_ui_metasprites[12];

BANKREF_EXTERN(level_ui)

extern const palette_color_t level_ui_palettes[32];
extern const uint8_t level_ui_tiles[384];

#endif
