//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_claimed_H
#define METASPRITE_claimed_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define claimed_TILE_ORIGIN 0
#define claimed_TILE_W 8
#define claimed_TILE_H 8
#define claimed_WIDTH 160
#define claimed_HEIGHT 144
#define claimed_TILE_COUNT 118
#define claimed_PALETTE_COUNT 1
#define claimed_COLORS_PER_PALETTE 4
#define claimed_TOTAL_COLORS 4
#define claimed_MAP_ATTRIBUTES 0
extern const unsigned char claimed_map[360];
#define claimed_map_attributes claimed_map

BANKREF_EXTERN(claimed)

extern const palette_color_t claimed_palettes[4];
extern const uint8_t claimed_tiles[1888];

#endif
