//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_enemy_H
#define METASPRITE_enemy_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define enemy_TILE_ORIGIN 0
#define enemy_TILE_W 8
#define enemy_TILE_H 16
#define enemy_WIDTH 16
#define enemy_HEIGHT 16
#define enemy_TILE_COUNT 32
#define enemy_PALETTE_COUNT 8
#define enemy_COLORS_PER_PALETTE 4
#define enemy_TOTAL_COLORS 32
#define enemy_PIVOT_X 8
#define enemy_PIVOT_Y 8
#define enemy_PIVOT_W 16
#define enemy_PIVOT_H 16
extern const metasprite_t* const enemy_metasprites[8];

BANKREF_EXTERN(enemy)

extern const palette_color_t enemy_palettes[32];
extern const uint8_t enemy_tiles[512];

#endif
