//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_level_H
#define METASPRITE_level_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define level_TILE_ORIGIN 0
#define level_TILE_W 8
#define level_TILE_H 16
#define level_WIDTH 8
#define level_HEIGHT 16
#define level_TILE_COUNT 22
#define level_PALETTE_COUNT 8
#define level_COLORS_PER_PALETTE 4
#define level_TOTAL_COLORS 32
#define level_PIVOT_X 4
#define level_PIVOT_Y 8
#define level_PIVOT_W 8
#define level_PIVOT_H 16
extern const metasprite_t* const level_metasprites[11];

BANKREF_EXTERN(level)

extern const palette_color_t level_palettes[32];
extern const uint8_t level_tiles[352];

#endif
