//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_next_level_H
#define METASPRITE_next_level_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define next_level_TILE_ORIGIN 0
#define next_level_TILE_W 8
#define next_level_TILE_H 8
#define next_level_WIDTH 160
#define next_level_HEIGHT 144
#define next_level_TILE_COUNT 236
#define next_level_PALETTE_COUNT 1
#define next_level_COLORS_PER_PALETTE 4
#define next_level_TOTAL_COLORS 4
#define next_level_MAP_ATTRIBUTES 0
extern const unsigned char next_level_map[360];
#define next_level_map_attributes next_level_map

BANKREF_EXTERN(next_level)

extern const palette_color_t next_level_palettes[4];
extern const uint8_t next_level_tiles[3776];

#endif
