//AUTOGENERATED FILE FROM png2asset
// Conversion args: /player.png -c /player.c -sw 16 -sh 16 -bpp 2 -noflip -keep_palette_order

#ifndef METASPRITE_player_H
#define METASPRITE_player_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define player_TILE_ORIGIN 0
#define player_TILE_W 8
#define player_TILE_H 16
#define player_WIDTH 16
#define player_HEIGHT 16
#define player_TILE_COUNT 28
#define player_PALETTE_COUNT 8
#define player_COLORS_PER_PALETTE 4
#define player_TOTAL_COLORS 32
#define player_PIVOT_X 8
#define player_PIVOT_Y 8
#define player_PIVOT_W 16
#define player_PIVOT_H 16
extern const metasprite_t* const player_metasprites[8];

BANKREF_EXTERN(player)

extern const palette_color_t player_palettes[32];
extern const uint8_t player_tiles[448];

#endif
