//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_spikes_H
#define METASPRITE_spikes_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define spikes_TILE_ORIGIN 0
#define spikes_TILE_W 8
#define spikes_TILE_H 16
#define spikes_WIDTH 8
#define spikes_HEIGHT 16
#define spikes_TILE_COUNT 4
#define spikes_PALETTE_COUNT 1
#define spikes_COLORS_PER_PALETTE 4
#define spikes_TOTAL_COLORS 4
#define spikes_PIVOT_X 4
#define spikes_PIVOT_Y 8
#define spikes_PIVOT_W 8
#define spikes_PIVOT_H 16
extern const metasprite_t* const spikes_metasprites[2];

BANKREF_EXTERN(spikes)

extern const palette_color_t spikes_palettes[4];
extern const uint8_t spikes_tiles[64];

#endif
