//AUTOGENERATED FILE FROM png2asset
// Conversion args: /stairs_sprite.png -c /stairs_sprite.c -sw 32 -sh 16 -bpp 2 -noflip -keep_palette_order -spr8x16

#ifndef METASPRITE_stairs_sprite_H
#define METASPRITE_stairs_sprite_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define stairs_sprite_TILE_ORIGIN 0
#define stairs_sprite_TILE_W 8
#define stairs_sprite_TILE_H 16
#define stairs_sprite_WIDTH 32
#define stairs_sprite_HEIGHT 16
#define stairs_sprite_TILE_COUNT 4
#define stairs_sprite_PALETTE_COUNT 8
#define stairs_sprite_COLORS_PER_PALETTE 4
#define stairs_sprite_TOTAL_COLORS 32
#define stairs_sprite_PIVOT_X 16
#define stairs_sprite_PIVOT_Y 8
#define stairs_sprite_PIVOT_W 32
#define stairs_sprite_PIVOT_H 16
extern const metasprite_t* const stairs_sprite_metasprites[1];

BANKREF_EXTERN(stairs_sprite)

extern const palette_color_t stairs_sprite_palettes[32];
extern const uint8_t stairs_sprite_tiles[64];

#endif
