//AUTOGENERATED FILE FROM png2asset
// Conversion args: /stamina.png -c /stamina.c -bpp 2 -noflip -keep_palette_order -spr8x16

#ifndef METASPRITE_stamina_H
#define METASPRITE_stamina_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define stamina_TILE_ORIGIN 0
#define stamina_TILE_W 8
#define stamina_TILE_H 16
#define stamina_WIDTH 104
#define stamina_HEIGHT 16
#define stamina_TILE_COUNT 26
#define stamina_PALETTE_COUNT 8
#define stamina_COLORS_PER_PALETTE 4
#define stamina_TOTAL_COLORS 32
#define stamina_PIVOT_X 52
#define stamina_PIVOT_Y 8
#define stamina_PIVOT_W 104
#define stamina_PIVOT_H 16
extern const metasprite_t* const stamina_metasprites[1];

BANKREF_EXTERN(stamina)

extern const palette_color_t stamina_palettes[32];
extern const uint8_t stamina_tiles[416];

#endif
