//AUTOGENERATED FILE FROM png2asset
// Conversion args: /tiles.png -c /tiles.c -map -bpp 2 -noflip -keep_palette_order

#ifndef METASPRITE_tiles_H
#define METASPRITE_tiles_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define tiles_TILE_ORIGIN 0
#define tiles_TILE_W 8
#define tiles_TILE_H 8
#define tiles_WIDTH 32
#define tiles_HEIGHT 5768
#define tiles_TILE_COUNT 151
#define tiles_PALETTE_COUNT 8
#define tiles_COLORS_PER_PALETTE 4
#define tiles_TOTAL_COLORS 32
#define tiles_MAP_ATTRIBUTES 0
extern const unsigned char tiles_map[2884];
#define tiles_map_attributes tiles_map

BANKREF_EXTERN(tiles)

extern const palette_color_t tiles_palettes[32];
extern const uint8_t tiles_tiles[2416];

#endif
