// AUTOGENERATED by scripts/generate_tiling_parts.py
#ifndef TILING_PARTS_H
#define TILING_PARTS_H

#include <stdint.h>

#define FLOOR_PARTS_PER_GROUP 16u
#define HATCH_PARTS_PER_GROUP 24u

extern const uint8_t floor_parts[4][FLOOR_PARTS_PER_GROUP];
extern const uint8_t hatch_parts[4][HATCH_PARTS_PER_GROUP];

#endif
