//AUTOGENERATED FILE FROM png2asset
// Conversion args: /victory.png -c /victory.c -bpp 2 -noflip -keep_palette_order -spr8x16

#ifndef METASPRITE_victory_H
#define METASPRITE_victory_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define victory_TILE_ORIGIN 0
#define victory_TILE_W 8
#define victory_TILE_H 16
#define victory_WIDTH 56
#define victory_HEIGHT 16
#define victory_TILE_COUNT 14
#define victory_PALETTE_COUNT 8
#define victory_COLORS_PER_PALETTE 4
#define victory_TOTAL_COLORS 32
#define victory_PIVOT_X 28
#define victory_PIVOT_Y 8
#define victory_PIVOT_W 56
#define victory_PIVOT_H 16
extern const metasprite_t* const victory_metasprites[1];

BANKREF_EXTERN(victory)

extern const palette_color_t victory_palettes[32];
extern const uint8_t victory_tiles[224];

#endif
